name: Build WoAiKaAdFree dylib

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:

  build:

    runs-on: macos-14


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Theos
        run: |

          rm -rf "$HOME/theos"

          git clone --recursive \
          https://github.com/theos/theos.git \
          "$HOME/theos"

          echo "THEOS=$HOME/theos" >> $GITHUB_ENV


      - name: Install SDK
        run: |

          rm -rf "$HOME/theos/sdks"

          git clone --depth=1 \
          https://github.com/theos/sdks.git \
          "$HOME/theos/sdks"


      - name: Install ldid
        run: |

          brew install ldid || true


      - name: Check Environment
        run: |

          export THEOS="$HOME/theos"

          echo "THEOS=$THEOS"

          ls -la "$THEOS"

          ls -la "$THEOS/sdks"



      - name: Build dylib
        run: |

          export THEOS="$HOME/theos"

          export THEOS_PACKAGE_SCHEME=rootless


          make clean


          make \
          FINALPACKAGE=1 \
          THEOS_PACKAGE_SCHEME=rootless



      - name: Find Build Output
        run: |

          echo "Searching dylib..."

          find . -name "*.dylib" -print



      - name: Upload dylib
        uses: actions/upload-artifact@v4

        with:

          name: WoAiKaAdFree-dylib

          path: |
            **/*.dylib

          if-no-files-found: error
